Default: &defaults
  database: consleak.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: consleak_test.sqlite3
  <<: *defaults

Staging:
  database: consleak_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: consleak_production.sqlite3
  poolsize: 100
  <<: *defaults
